<MyLabel@Label>:
    font_size:"12sp"
    markup: True
    valign:"top"
<MyButton@ToggleButton>:
    border:4,4,4,4
    on_press:root.buttonChange()
    #background_color:0,0,0,1
    #background_normal:"icons/patiSiyah.png"
    #background_down:"icons/patiYesil.png"
<MySlider@Slider>:
    orientation:'vertical'
    value_track:True
    value_track_color:0, 1, 0, 1
    padding:0

<AnaEkran@TabbedPanel>:
    #size_hint: .5, .5
    #pos_hint: {'center_x': .5, 'center_y': .5}
    do_default_tab: False
    tab_pos: 'left_top'
    tab_height:30
    tab_width:60

    #arka plan resmi
    #background_color: (1, 1, 1, 1) #50% translucent red
    #border: [0, 0, 0, 0]
    #background_image: '~/Pictures/Images/zemin.jpeg'

    #tempVal: temp_label

    TabbedPanelItem:
        text: 'Home'
        #border:8,8,0,0
        #background_down:"icons/home-icon.png"
        #background_normal:"icons/icons8-light-40.png"
        #clearcolor: (1, 0, 0, 1)
        background_color:1,0,0,1
        #humVal:

        BoxLayout:
            orientation: "vertical"
            GridLayout:
                cols:8
                padding:60,30,60,0
                spacing:15,0
                MyButton:
                    #background_normal:"icons/icons8-lightBlue-40.png"
                    #background_down:"icons/icons8-light-40.png"
                    #on_press:root.buttonChange()
                    pin_number:5
                    id:b1
                MyButton:
                    #background_normal:"icons/icons8-sunlightBlue-30.png"
                    #background_down:"icons/icons8-sunlight-30.png"
                    pin_number:6
                    id:b2
                MyButton:
                    pin_number:13
                    id:b3
                MyButton:
                    pin_number:16
                    id:b4
                MyButton:
                    pin_number:19
                    id:b5
                MyButton:
                    pin_number:20
                    id:b6
                MyButton:
                    pin_number:21
                    id:b7
                MyButton:
                    pin_number:26
                    id:b8
             
                
                MyLabel:
                    text:"Lighting"

                MyLabel:
                    text:"Neb"
                
                MyLabel:
                    text:"Hum"

                MyLabel:
                    text:"Carbon\nTemp"

                MyLabel:
                    text:"Serum\nTemp"
                
                MyLabel:
                    text:"Fan"

                MyLabel:
                    text:"UV\nLighting"

                MyLabel:
                    text:"Ozon"

            GridLayout:
                cols:5
                padding:80,0,80,0
                spacing:40,0
                MySlider:
                    id:sld1
                    min: 1
                    max: 60
                    #value: 0
                    on_value:root.ids.uv_label.text="Neb \n {:d} min".format(int(self.value))
                MySlider:
                    min:20
                    max:60
                    id:sld2
                    on_value:root.ids.hum_lbl.text ="Hum\n%{:d}rH".format(int(self.value))
                MySlider:
                    min:20
                    max:40
                    id:sld3
                    on_value:root.ids.temp_lbl.text ="Temp\n{:2.1f}°C".format(self.value)
                MySlider:
                    min:20
                    max:40
                    id:sld4
                    on_value:root.ids.serumTemp_lbl.text ="SerumTemp\n{:2.1f}°C".format(self.value)
                MySlider:
                    id:sld5
                    min:1
                    max:60
                    on_value:root.ids.ozon_lbl.text ="Ozon\n{:d} min".format(int(self.value))
                Label:
                    id:uv_label
                    text:"Neb \n {:d} min".format(int(root.ids.sld1.value))
                    #markup:True
                    #text:"[color=#32EAED]Lighting[/color]\n" #{:^17d}".format(int(root.ids.lightSliderId.value))
                Label:
                    id:hum_lbl
                    text:"Hum\n%{:d}rH".format(int(root.ids.sld2.value))
                Label:
                    id:temp_lbl
                    text:"Temp\n{:2.1f}°C".format(root.ids.sld3.value)
                Label:
                    id:serumTemp_lbl
                    text:"SerumTemp\n{:2.1f}°C".format(root.ids.sld4.value)
                Label:
                    id:ozon_lbl
                    text:"Ozon\n{:d} min".format(int(root.ids.sld5.value))

            BoxLayout:
                padding:40,0,40,40
                
                Image:
                
                    source:'/home/pi/Pictures/Images/antalyaKafes.jpg'

                #BoxLayout:
                #FloatLayout:

                Label:
                    id: hum_label
                    font_size: "50sp"
                    #pos_hint: {"right":1,"top":1}
                    color: 0,1,0,1
                    outline_color:0,1,0
                    text: "--"
                Label:
                    id: temp_label
                    color: 0.1,0.9,0.9,1
                    font_size: "50sp"
                    #pos_hint: {"right":1,"top":.6}
                    text: "--"
                Image:
                    
                    source:'/home/pi/Pictures/Images/firma.jpg'
            
                #size_hint:.1,None
                Button:
                    text:"Close"
                    size_hint:None,.2
                    pos:750,5
                    width:50
                    on_press: root.cikis()
            
    TabbedPanelItem:
        text: 'Settings'
        background_color:0,1,0,1

        #Slider:
            #min: 0
            #max: 1
            #value: 0.5
            #on_value: color_label.text = "Renk " + str(self.value); root.slider_colors = (self.value for i in xrange(3))

        GridLayout:
            cols:2
            padding:80,80,80,80
            spacing:40,0
            MySlider:
                id:sld6
                step:1
                min:1
                max:60
                on_value:root.ids.uvInt_lbl.text="Neb Interval \n{:02d} min".format(int(self.value))
            MySlider:
                id:sld7
                step:0.25
                min:0.25
                max:15
                on_value:root.ids.ozonInt_lbl.text="Ozon interval\n{:2.2f} hours".format(float(self.value))
            Label:
                id:uvInt_lbl
                #markup:True
                #text:"[color=#32EAED]Lighting[/color]\n{:^17d}".format(int(root.ids.lightSliderId.value))
                text:"Neb interval\n"
            Label:
                id:ozonInt_lbl
                text:"Ozon interval\n"
            




#<GirisEkran>:
#    KontrolEkrani:
#       name: "Ekran 1"
#    AyarEkrani:
#        name: "Ekran2"


